name: "Bug report"
description: Create a report to help us improve
labels: ["type: bug"]
body:
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows 11 / macOS 14 / Ubuntu 22.04"
    validations:
      required: true
  - type: input
    id: jdk
    attributes:
      label: JDK version
      placeholder: "e.g., 17.0.9"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Include steps to reproduce and what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      render: shell
